# Generated by Django 5.2 on 2025-04-24 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.platform'),
        ),
    ]
